env:
  browser: true
  commonjs: true
  es6: true

extends:
- airbnb

parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module

plugins:
  - import
  - jsx-a11y
  - react

rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
