# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1daf7611a4f224938832747462e09e092b04ab691b5e65aebb8d4e92ac497a4ecb48760666ff66ba8d0294394d5a73d9ffe01faa79497e40aa48d83c4c75a796
  facebook_app_key: <%= ENV['FACEBOOK_APP_KEY'] %>
  facebook_secret_key: <%= ENV['FACEBOOK_SECRET_KEY'] %>

test:
  secret_key_base: 4e3791a53e3e4339bdf67a31259e0e1b4a4a2a7ea21840dc50f4f0fc6cb16fd6215abe9efa68121813b80506044a022e244a41bdcb0645cca2e36a0083f3dd95
  facebook_app_key: <%= ENV['FACEBOOK_APP_KEY'] %>
  facebook_secret_key: <%= ENV['FACEBOOK_SECRET_KEY'] %>

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_key: <%= ENV['FACEBOOK_APP_KEY'] %>
  facebook_secret_key: <%= ENV['FACEBOOK_SECRET_KEY'] %>
